/*
NOMES:
Arthur Leme de Souza Palma, Caio Fabricio dos Santos, Matheus Henrique Reich
*/

exception InvalidKey
{
	string keyError;
};

interface CEtcd
{
	readonly attribute string id;

	boolean put(in string key, in string val);
	string get(in string key) raises(InvalidKey);
	void del(in string key) raises(InvalidKey);
	// oneway void shutDown();
};